import type { Metadata } from "next";

import "./globals.css";
import { Nav } from "@/components/ui/nav";
import AuthProvider from "./utils/AuthProvider";
//import {Toaster} from 'sonner';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          {children}
          {/*<Toaster richColors/>*/}
        </AuthProvider>
      </body>
    </html>
  );
}
