FROM python:3.12-slim

WORKDIR /app/py-be

COPY py-be/pyproject.toml py-be/poetry.lock ./

RUN pip install poetry

RUN poetry install --no-root

COPY py-be/ ./

RUN chmod +x run_tests.sh

ENTRYPOINT ["./run_tests.sh"]