// contractGroupedBlocks.ts
import type { ComponentType, SVGProps } from "react";
import {
  DollarSign,
  Flame,
  ArrowRightLeft,
  CheckSquare,
  Tag,
  Eye,
  Sliders,
  PauseCircle,
  Edit2,
  Copy,
  Percent,
  Activity,
  PieChart,
  UserX,
  Maximize2,
  Settings,
  ImageIcon,
  Layers,
  Hash,
  PlusCircle,
  Megaphone,
  Calendar,
  CreditCard,
  CornerUpLeft,
  Target,
  Clock,
  FilePlus,
  PlayCircle,
  Users,
  PiggyBank,
  FileText,
  History,
  Key,
  AlertCircle,
  Gift,
  Ticket,
  Shuffle,
  Award,
  Repeat,
  Send,
  FileCheck,
  TreePine,
  Download,
  Zap,
  ShieldCheck,
  Lock,
  UserPlus,
  UserMinus,
  X,
  Copy as CopyMultisig,
  CheckCircle,
  ShieldOff,
  Wallet,
  Layers as LayersWallet,
  Briefcase,
  BookOpen,
  AlertTriangle,
  CalendarPlus,
  ChevronDown,
  ArrowRightCircle,
  XCircle,
  AlertTriangle as AlertTriangleVesting,
  Calculator,
  PlayCircle as PlayCircleStaking,
  StopCircle,
  Tractor,
  Droplet,
  Unlock,
  Bell,
  DownloadCloud,
  UploadCloud,
} from "lucide-react";

export interface BlockDef {
  id: string;
  content: string;
  icon: ComponentType<SVGProps<SVGSVGElement>>;
}

export interface SectionDef {
  icon: ComponentType<SVGProps<SVGSVGElement>>;
  blocks: BlockDef[];
}

const contractGroupedBlocks: Record<string, SectionDef> = {
  "Token (ERC-20)": {
    icon: ArrowRightLeft,
    blocks: [
      { id: "mintTokens", content: "Mint Tokens", icon: DollarSign },
      { id: "burnTokens", content: "Burn Tokens", icon: Flame },
      { id: "transferTokens", content: "Transfer Tokens", icon: ArrowRightLeft },
      { id: "approveTokenSpending", content: "Approve Token Spending", icon: CheckSquare },
      { id: "setTokenPrice", content: "Set Token Price", icon: Tag },
      { id: "tokenBalanceCheck", content: "Token Balance Check", icon: Eye },
      { id: "setTransferLimits", content: "Set Transfer Limits", icon: Sliders },
      { id: "pauseTokenTransfers", content: "Pause Token Transfers", icon: PauseCircle },
      { id: "setTokenMetadata", content: "Set Token Metadata", icon: Edit2 },
      { id: "bulkTransferTokens", content: "Bulk Transfer Tokens", icon: Copy },
    ],
  },

  "Token (ERC-20 Deflationary)": {
    icon: Percent,
    blocks: [
      { id: "autoBurnOnTransfer", content: "Auto Burn on Transfer", icon: Percent },
      { id: "manualBurnTokens", content: "Manual Burn Tokens", icon: Flame },
      { id: "setBurnRate", content: "Set Burn Rate", icon: Sliders },
      { id: "burnEventTracking", content: "Burn Event Tracking", icon: Activity },
      { id: "setTransactionFees", content: "Set Transaction Fees", icon: Tag },
      { id: "feeDistribution", content: "Fee Distribution", icon: PieChart },
      { id: "excludeFromFees", content: "Exclude from Fees", icon: UserX },
      { id: "setMaxTransaction", content: "Set Max Transaction", icon: Maximize2 },
      { id: "reflectionRewards", content: "Reflection Rewards", icon: Award },
      { id: "updateBurnParameters", content: "Update Burn Parameters", icon: Settings },
    ],
  },

  "NFT Collection (ERC-721)": {
    icon: ImageIcon,
    blocks: [
      { id: "mintNFT", content: "Mint NFT", icon: ImageIcon },
      { id: "setNFTMetadata", content: "Set NFT Metadata", icon: Edit2 },
      { id: "transferNFT", content: "Transfer NFT", icon: ArrowRightLeft },
      { id: "burnNFT", content: "Burn NFT", icon: Flame },
      { id: "setRoyaltyFee", content: "Set Royalty Fee", icon: Percent },
      { id: "batchMintNFTs", content: "Batch Mint NFTs", icon: Layers },
      { id: "setMintingPrice", content: "Set Minting Price", icon: Tag },
      { id: "whitelistMinting", content: "Whitelist Minting", icon: UserPlus },
      { id: "setMaxSupply", content: "Set Max Supply", icon: Maximize2 },
      { id: "enableDisableTrading", content: "Enable/Disable Trading", icon: Sliders },
      { id: "setBaseURI", content: "Set Base URI", icon: Tag },
      { id: "revealCollection", content: "Reveal Collection", icon: Eye },
    ],
  },

  "NFT Collection (ERC-1155)": {
    icon: Copy,
    blocks: [
      { id: "mintTokenBatch", content: "Mint Token Batch", icon: Copy },
      { id: "setTokenSupply", content: "Set Token Supply", icon: Sliders },
      { id: "burnTokenBatch", content: "Burn Token Batch", icon: Flame },
      { id: "setIndividualPrices", content: "Set Individual Prices", icon: Tag },
      { id: "batchTransfer", content: "Batch Transfer", icon: ArrowRightLeft },
      { id: "setTokenMetadata1155", content: "Set Token Metadata", icon: Edit2 },
      { id: "createTokenType", content: "Create Token Type", icon: PlusCircle },
      { id: "setFungibilityRules", content: "Set Fungibility Rules", icon: Hash },
      { id: "bulkOperations1155", content: "Bulk Operations", icon: Layers },
      { id: "tokenTypePermissions", content: "Token Type Permissions", icon: ShieldCheck },
    ],
  },

  "Crowdsale (ICO)": {
    icon: Megaphone,
    blocks: [
      { id: "createCampaign", content: "Create Campaign", icon: Megaphone },
      { id: "setSaleTimeline", content: "Set Sale Timeline", icon: Calendar },
      { id: "setTokenPriceICO", content: "Set Token Price", icon: Tag },
      { id: "acceptPayments", content: "Accept Payments", icon: CreditCard },
      { id: "distributeTokens", content: "Distribute Tokens", icon: ArrowRightLeft },
      { id: "refundContributors", content: "Refund Contributors", icon: CornerUpLeft },
      { id: "setMinimumGoal", content: "Set Minimum Goal", icon: Target },
      { id: "earlyBirdPricing", content: "Early Bird Pricing", icon: Clock },
      { id: "whitelistContributors", content: "Whitelist Contributors", icon: UserPlus },
      { id: "setContributionLimits", content: "Set Contribution Limits", icon: Sliders },
      { id: "campaignAnalytics", content: "Campaign Analytics", icon: PieChart },
      { id: "emergencyStopSale", content: "Emergency Stop Sale", icon: PauseCircle },
    ],
  },

  "DAO (Decentralized Autonomous Organization)": {
    icon: FilePlus,
    blocks: [
      { id: "createProposal", content: "Create Proposal", icon: FilePlus },
      { id: "voteOnProposal", content: "Vote on Proposal", icon: CheckSquare },
      { id: "executeProposal", content: "Execute Proposal", icon: PlayCircle },
      { id: "delegateVotingPower", content: "Delegate Voting Power", icon: Users },
      { id: "setVotingParameters", content: "Set Voting Parameters", icon: Sliders },
      { id: "treasuryManagement", content: "Treasury Management", icon: PiggyBank },
      { id: "memberManagement", content: "Member Management", icon: Users },
      { id: "proposalTemplates", content: "Proposal Templates", icon: FileText },
      { id: "votingHistory", content: "Voting History", icon: History },
      { id: "multiSigApproval", content: "Multi-Signature Approval", icon: Key },
      { id: "timeLockProposals", content: "Time Lock Proposals", icon: Clock },
      { id: "emergencyGovernance", content: "Emergency Governance", icon: AlertCircle },
    ],
  },

  "Blockchain Lottery": {
    icon: Gift,
    blocks: [
      { id: "createLottery", content: "Create Lottery", icon: Gift },
      { id: "buyTicket", content: "Buy Ticket", icon: Ticket },
      { id: "generateRandomWinner", content: "Generate Random Winner", icon: Shuffle },
      { id: "distributePrizes", content: "Distribute Prizes", icon: ArrowRightLeft },
      { id: "setTicketPriceLottery", content: "Set Ticket Price", icon: Tag },
      { id: "setPrizeStructure", content: "Set Prize Structure", icon: PieChart },
      { id: "scheduleDraw", content: "Schedule Draw", icon: Calendar },
      { id: "refundTickets", content: "Refund Tickets", icon: CornerUpLeft },
      { id: "lotteryHistory", content: "Lottery History", icon: History },
      { id: "multiPrizeLottery", content: "Multi-Prize Lottery", icon: Award },
      { id: "recurringLottery", content: "Recurring Lottery", icon: Repeat },
      { id: "prizePoolManagement", content: "Prize Pool Management", icon: PiggyBank },
    ],
  },

  "AirDrop (Multisender)": {
    icon: Send,
    blocks: [
      { id: "bulkSendTokens", content: "Bulk Send Tokens", icon: Send },
      { id: "csvImportRecipients", content: "CSV Import Recipients", icon: FileCheck },
      { id: "setDistributionRules", content: "Set Distribution Rules", icon: Sliders },
      { id: "merkleTreeAirdrop", content: "Merkle Tree Airdrop", icon: TreePine },
      { id: "claimTokensAirdrop", content: "Claim Tokens", icon: Download },
      { id: "whitelistRecipients", content: "Whitelist Recipients", icon: UserPlus },
      { id: "scheduleAirdrop", content: "Schedule Airdrop", icon: Calendar },
      { id: "airdropAnalytics", content: "Airdrop Analytics", icon: PieChart },
      { id: "gasOptimization", content: "Gas Optimization", icon: Zap },
      { id: "preventDoubleClaims", content: "Prevent Double Claims", icon: ShieldCheck },
      { id: "conditionalAirdrops", content: "Conditional Airdrops", icon: Layers },
      { id: "snapshotBalances", content: "Snapshot Balances", icon: Eye },
    ],
  },

  "Multisig": {
    icon: Lock,
    blocks: [
      { id: "createMultisigWallet", content: "Create Multisig Wallet", icon: Lock },
      { id: "addSigners", content: "Add Signers", icon: UserPlus },
      { id: "removeSigners", content: "Remove Signers", icon: UserMinus },
      { id: "setSignatureThreshold", content: "Set Signature Threshold", icon: Sliders },
      { id: "proposeTransaction", content: "Propose Transaction", icon: FilePlus },
      { id: "approveTransaction", content: "Approve Transaction", icon: CheckSquare },
      { id: "executeTransaction", content: "Execute Transaction", icon: PlayCircle },
      { id: "revokeApproval", content: "Revoke Approval", icon: X },
      { id: "transactionHistoryMultisig", content: "Transaction History", icon: History },
      { id: "emergencyRecovery", content: "Emergency Recovery", icon: ShieldOff },
      { id: "batchTransactions", content: "Batch Transactions", icon: CopyMultisig },
      { id: "signatureVerification", content: "Signature Verification", icon: CheckCircle },
    ],
  },

  "Multisig Wallet": {
    icon: Wallet,
    blocks: [
      { id: "walletBalanceDisplay", content: "Wallet Balance Display", icon: Wallet },
      { id: "multiAssetSupport", content: "Multi-Asset Support", icon: LayersWallet },
      { id: "spendingLimits", content: "Spending Limits", icon: Sliders },
      { id: "recurringPayments", content: "Recurring Payments", icon: Repeat },
      { id: "budgetManagement", content: "Budget Management", icon: Briefcase },
      { id: "contactManagement", content: "Contact Management", icon: UserPlus },
      { id: "transactionTemplates", content: "Transaction Templates", icon: FileText },
      { id: "walletAnalytics", content: "Wallet Analytics", icon: PieChart },
      { id: "addressBook", content: "Address Book", icon: BookOpen },
      { id: "gasOptimizationWallet", content: "Gas Optimization", icon: Zap },
      { id: "securityAlerts", content: "Security Alerts", icon: AlertTriangle },
      { id: "backupRecovery", content: "Backup and Recovery", icon: Download },
    ],
  },

  "Vesting": {
    icon: CalendarPlus,
    blocks: [
      { id: "createVestingSchedule", content: "Create Vesting Schedule", icon: CalendarPlus },
      { id: "linearVestingRelease", content: "Linear Vesting Release", icon: ArrowRightCircle },
      { id: "cliffVesting", content: "Cliff Vesting", icon: ChevronDown },
      { id: "releaseTokensVesting", content: "Release Tokens", icon: ArrowRightCircle },
      { id: "revokeVesting", content: "Revoke Vesting", icon: XCircle },
      { id: "setVestingParameters", content: "Set Vesting Parameters", icon: Sliders },
      { id: "beneficiaryManagement", content: "Beneficiary Management", icon: Users },
      { id: "vestingAnalytics", content: "Vesting Analytics", icon: PieChart },
      { id: "multiTokenVesting", content: "Multi-Token Vesting", icon: Layers },
      { id: "conditionalVesting", content: "Conditional Vesting", icon: Zap },
      { id: "vestingTemplates", content: "Vesting Templates", icon: FileText },
      { id: "emergencyVest", content: "Emergency Vest", icon: AlertTriangleVesting },
    ],
  },

  "Staking": {
    icon: PlayCircleStaking,
    blocks: [
      { id: "startStaking", content: "Start Staking", icon: PlayCircleStaking },
      { id: "stopStaking", content: "Stop Staking", icon: StopCircle },
      { id: "claimRewards", content: "Claim Rewards", icon: Gift },
      { id: "setStakingPool", content: "Set Staking Pool", icon: Sliders },
      { id: "updateRewardRate", content: "Update Reward Rate", icon: Sliders },
      { id: "calculateRewards", content: "Calculate Rewards", icon: Calculator },
      { id: "setStakingDuration", content: "Set Staking Duration", icon: Clock },
      { id: "earlyWithdrawalPenalty", content: "Penalty for Early Withdrawal", icon: Percent },
      { id: "compoundRewards", content: "Compound Rewards", icon: Repeat },
      { id: "stakingAnalytics", content: "Staking Analytics", icon: PieChart },
      { id: "multiTokenStaking", content: "Multi-Token Staking", icon: Layers },
      { id: "boostRewards", content: "Boost Rewards", icon: Zap },
    ],
  },

  "Farming": {
    icon: Tractor,
    blocks: [
      { id: "createFarm", content: "Create Farm", icon: Tractor },
      { id: "addLiquidityToFarm", content: "Add Liquidity to Farm", icon: Droplet },
      { id: "removeLiquidityFromFarm", content: "Remove Liquidity from Farm", icon: Droplet },
      { id: "harvestRewards", content: "Harvest Rewards", icon: Tractor },
      { id: "setFarmMultipliers", content: "Set Farm Multipliers", icon: Sliders },
      { id: "lpTokenStaking", content: "LP Token Staking", icon: Droplet },
      { id: "multiRewardFarming", content: "Multi-Reward Farming", icon: Layers },
      { id: "farmAnalytics", content: "Farm Analytics", icon: PieChart },
      { id: "boostFarming", content: "Boost Farming", icon: Zap },
      { id: "autoCompoundFarming", content: "Auto-Compound Farming", icon: Repeat },
      { id: "farmLifecycleManagement", content: "Farm Lifecycle Management", icon: Calendar },
      { id: "emissionScheduling", content: "Emission Scheduling", icon: Clock },
    ],
  },

  "Token Locker": {
    icon: Lock,
    blocks: [
      { id: "lockTokens", content: "Lock Tokens", icon: Lock },
      { id: "setLockDuration", content: "Set Lock Duration", icon: Clock },
      { id: "unlockTokens", content: "Unlock Tokens", icon: Unlock },
      { id: "extendLockPeriod", content: "Extend Lock Period", icon: Repeat },
      { id: "emergencyUnlock", content: "Emergency Unlock", icon: AlertCircle },
      { id: "lockAnalytics", content: "Lock Analytics", icon: PieChart },
      { id: "batchLockTokens", content: "Batch Lock Tokens", icon: Copy },
      { id: "lockConditions", content: "Lock Conditions", icon: Sliders },
      { id: "lockBeneficiaries", content: "Lock Beneficiaries", icon: Users },
      { id: "lockTemplates", content: "Lock Templates", icon: FileText },
      { id: "proofOfLock", content: "Proof of Lock", icon: ShieldCheck },
      { id: "lockNotifications", content: "Lock Notifications", icon: Bell },
    ],
  },

  "Liquidity Locker": {
    icon: Lock,
    blocks: [
      { id: "lockLPTokens", content: "Lock LP Tokens", icon: Lock },
      { id: "setLiquidityLockDuration", content: "Set Liquidity Lock Duration", icon: Clock },
      { id: "unlockLPTokens", content: "Unlock LP Tokens", icon: Unlock },
      { id: "lockVerification", content: "Lock Verification", icon: CheckCircle },
      { id: "extendLiquidityLock", content: "Extend Liquidity Lock", icon: Repeat },
      { id: "lpLockAnalytics", content: "LP Lock Analytics", icon: PieChart },
      { id: "teamLockManagement", content: "Team Lock Management", icon: Users },
      { id: "lockCertificates", content: "Lock Certificates", icon: ShieldCheck },
      { id: "partialUnlock", content: "Partial Unlock", icon: Unlock },
      { id: "lockRenewals", content: "Lock Renewals", icon: Repeat },
      { id: "communityLockVoting", content: "Community Lock Voting", icon: Users },
      { id: "lockInsurance", content: "Lock Insurance", icon: ShieldCheck },
    ],
  },

  "ERC-4626 (Tokenized Vaults)": {
    icon: CreditCard,
    blocks: [
      { id: "createVault", content: "Create Vault", icon: CreditCard },
      { id: "depositAssets", content: "Deposit Assets", icon: DownloadCloud },
      { id: "withdrawAssets", content: "Withdraw Assets", icon: UploadCloud },
      { id: "mintVaultShares", content: "Mint Vault Shares", icon: DollarSign },
      { id: "redeemVaultShares", content: "Redeem Vault Shares", icon: ArrowRightLeft },
      { id: "calculateSharePrice", content: "Calculate Share Price", icon: Calculator },
      { id: "vaultStrategyManagement", content: "Vault Strategy Management", icon: Sliders },
      { id: "performanceFees", content: "Performance Fees", icon: Percent },
      { id: "vaultAnalytics", content: "Vault Analytics", icon: PieChart },
      { id: "emergencyVaultPause", content: "Emergency Vault Pause", icon: PauseCircle },
      { id: "vaultRebalancing", content: "Vault Rebalancing", icon: Repeat },
      { id: "multiAssetVaults", content: "Multi-Asset Vaults", icon: Layers },
    ],
  },
};

export default contractGroupedBlocks;
