import {
  ArrowRightLeft,
  Banknote,
  BarChart3,
  Briefcase,
  LineChartIcon as ChartLine,
  Clock,
  Coins,
  Droplets,
  Fan,
  Flag,
  Gift,
  HandCoins,
  History,
  Landmark,
  LockKeyhole,
  MessageSquare,
  Package,
  PiggyBank,
  Plane,
  Power,
  Sprout,
  Tractor,
  TrendingDown,
  TrendingUp,
  Users,
  Zap,
  DollarSign,
  Shield,
  UserCheck,
  UserX,
  CheckSquare,
  Key,
  PauseCircle,
  PlayCircle,
  Globe,
  Edit,
  Download,
  Upload,
  Code,
} from "lucide-react";

const blockTypes = [
  // Trigger Actions
  {
    id: "start",
    content: "Upon Initialise",
    color: "bg-[#451805]",
    borderColor: "border-[#8A5035]",
    hoverBorderColor: "hover:border-[#BE5B2A]",
    icon: Flag,
  },
  {
    id: "end",
    content: "Disconnect",
    color: "bg-[#451805]",
    borderColor: "border-[#8A5035]",
    hoverBorderColor: "hover:border-[#BE5B2A]",
    icon: Power,
  },

  // Token Actions
  {
    id: "swap",
    content: "Swap Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: ArrowRightLeft,
  },
  {
    id: "stake",
    content: "Stake Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Landmark,
  },
  {
    id: "allocate",
    content: "Allocate Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: HandCoins,
  },
  {
    id: "startYieldFarming",
    content: "Start Yield Farming",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Sprout,
  },
  {
    id: "stopYieldFarming",
    content: "Stop Yield Farming",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Tractor,
  },
  {
    id: "lendTokens",
    content: "Lend Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: PiggyBank,
  },
  {
    id: "borrowTokens",
    content: "Borrow Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Coins,
  },
  {
    id: "repayLoan",
    content: "Repay Loan",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Banknote,
  },
  {
    id: "claimTokens",
    content: "Claim Tokens",
    color: "bg-[#142321]",
    borderColor: "border-[#245C3D]",
    hoverBorderColor: "hover:border-[#6AFB8E]",
    icon: Gift,
  },

  // Liquidity
  {
    id: "liquidity",
    content: "Add Liquidity",
    color: "bg-[#17273E]",
    borderColor: "border-[#2F5B87]",
    hoverBorderColor: "hover:border-[#87C6E0]",
    icon: Droplets,
  },
  {
    id: "createStakingPool",
    content: "Create Staking Pool",
    color: "bg-[#17273E]",
    borderColor: "border-[#2F5B87]",
    hoverBorderColor: "hover:border-[#87C6E0]",
    icon: Users,
  },

  // Portfolio Management
  {
    id: "rebalancePortfolio",
    content: "Rebalance Portfolio",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: BarChart3,
  },
  {
    id: "setRebalanceFrequency",
    content: "Set Rebalance Frequency",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: Clock,
  },
  {
    id: "createCustomIndex",
    content: "Create Custom Index",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: Package,
  },
  {
    id: "setStopLoss",
    content: "Set Stop Loss",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: TrendingDown,
  },
  {
    id: "setTakeProfit",
    content: "Set Take Profit",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: TrendingUp,
  },
  {
    id: "setStrategy",
    content: "Set Strategy",
    color: "bg-[#2F1E3A]",
    borderColor: "border-[#472A56]",
    hoverBorderColor: "hover:border-[#663E7D]",
    icon: Briefcase,
  },

  // Governance
  {
    id: "governance",
    content: "Vote on Proposal",
    color: "bg-[#21173E]",
    borderColor: "border-[#35285B]",
    hoverBorderColor: "hover:border-[#A57BBE]",
    icon: MessageSquare,
  },
  {
    id: "createVesting",
    content: "Create Vesting",
    color: "bg-[#21173E]",
    borderColor: "border-[#35285B]",
    hoverBorderColor: "hover:border-[#A57BBE]",
    icon: LockKeyhole,
  },

  // Events
  {
    id: "event",
    content: "On Event Outcome",
    color: "bg-[#4A0505]",
    borderColor: "border-[#791919]",
    hoverBorderColor: "hover:border-[#BC2F2F]",
    icon: Fan,
  },
  {
    id: "executeFlashLoan",
    content: "Execute Flash Loan",
    color: "bg-[#4A0505]",
    borderColor: "border-[#791919]",
    hoverBorderColor: "hover:border-[#BC2F2F]",
    icon: Zap,
  },
  {
    id: "initiateAirdrop",
    content: "Initiate Airdrop",
    color: "bg-[#4A0505]",
    borderColor: "border-[#791919]",
    hoverBorderColor: "hover:border-[#BC2F2F]",
    icon: Plane,
  },

  // Analytics
  {
    id: "getTransactionHistory",
    content: "Get Transaction History",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: History,
  },
  {
    id: "getPortfolioAnalytics",
    content: "Get Portfolio Analytics",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: ChartLine,
  },

  // New Common Functions
  {
    id: "mintTokens",
    content: "Mint Tokens",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: DollarSign,
  },
  {
    id: "burnTokens",
    content: "Burn Tokens",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Shield,
  },
  {
    id: "freezeAccount",
    content: "Freeze Account",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: UserX,
  },
  {
    id: "unfreezeAccount",
    content: "Unfreeze Account",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: UserCheck,
  },
  {
    id: "approveSpending",
    content: "Approve Spending",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: CheckSquare,
  },
  {
    id: "transferOwnership",
    content: "Transfer Ownership",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Key,
  },
  {
    id: "pauseContract",
    content: "Pause Contract",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: PauseCircle,
  },
  {
    id: "unpauseContract",
    content: "Unpause Contract",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: PlayCircle,
  },
  {
    id: "setOracle",
    content: "Set Oracle",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Globe,
  },
  {
    id: "updateMetadata",
    content: "Update Metadata",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Edit,
  },
  {
    id: "withdrawFunds",
    content: "Withdraw Funds",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Download,
  },
  {
    id: "depositFunds",
    content: "Deposit Funds",
    color: "bg-[#1E3A3A]",
    borderColor: "border-[#2A5656]",
    hoverBorderColor: "hover:border-[#3E7D7D]",
    icon: Upload,
  },
  // Custom template for custom blocks
  {
    id: "custom",
    content: "Custom Block",
    color: "bg-[#3C3C3C]",
    borderColor: "border-[#6C6C6C]",
    hoverBorderColor: "hover:border-[#9C9C9C]",
    icon: Code,
  },
];

// Group blocks into categories for the sidebar
const groupedBlocks = {
  "Trigger Actions": blockTypes.filter((block) =>
    ["start", "end", "disconnect", "initialise"].includes(block.id)
  ),
  "Token Actions": blockTypes.filter((block) =>
    [
      "swap",
      "stake",
      "allocate",
      "startYieldFarming",
      "stopYieldFarming",
      "lendTokens",
      "borrowTokens",
      "repayLoan",
      "claimTokens",
    ].includes(block.id)
  ),
  Liquidity: blockTypes.filter((block) =>
    ["liquidity", "createStakingPool"].includes(block.id)
  ),
  "Portfolio Management": blockTypes.filter((block) =>
    [
      "rebalancePortfolio",
      "setRebalanceFrequency",
      "createCustomIndex",
      "setStopLoss",
      "setTakeProfit",
      "setStrategy",
    ].includes(block.id)
  ),
  Governance: blockTypes.filter((block) =>
    ["governance", "createVesting"].includes(block.id)
  ),
  Events: blockTypes.filter((block) =>
    ["event", "executeFlashLoan", "initiateAirdrop"].includes(block.id)
  ),
  Analytics: blockTypes.filter((block) =>
    ["getTransactionHistory", "getPortfolioAnalytics"].includes(block.id)
  ),
  "Common Functions": blockTypes.filter((block) =>
    [
      "mintTokens",
      "burnTokens",
      "freezeAccount",
      "unfreezeAccount",
      "approveSpending",
      "transferOwnership",
      "pauseContract",
      "unpauseContract",
      "setOracle",
      "updateMetadata",
      "withdrawFunds",
      "depositFunds",
    ].includes(block.id)
  ),
  Custom: blockTypes.filter((block) => ["custom"].includes(block.id)),
};

export default groupedBlocks;
